# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Static Budget Portal
email: info@openup.org.za
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - env
  - generate
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - 
    scope:
      path: "2015-16"
    values:
      financial_year: 2015-16
      years: [
        ['2015-16', '/2015-16/departments', 'active'],
        ['2016-17', '/2016-17/departments', 'link'],
        ['2017-18', '/2017-18/departments', 'link'],
      ]
      navbar: [
        ['home-icon', '/', false, true],
        ['Departments', '/2017-18/departments', true, false, true],
        ['About', '/2017-18/about', false, false]
      ]
  -
    scope:
      path: "2016-17"
    values:
      financial_year: 2016-17
      years: [
        ['2015-16', '/2015-16/departments', 'link'],
        ['2016-17', '/2016-17/departments', 'active'],
        ['2017-18', '/2017-18/departments', 'link'],
      ]
      navbar: [
        ['home-icon', '/2016-17', false, true],
        ['Departments', '/2016-17/departments', true, false, true],
        ['About', '/2016-17/about', false, false]
      ]
  -
    scope:
      path: "2017-18"
    values:
      financial_year: 2017-18
      years: [
        ['2015-16', '/2015-16/departments', 'link'],
        ['2016-17', '/2016-17/departments', 'link'],
        ['2017-18', '/2017-18/departments', 'active'],
      ]
      navbar: [
        ['home-icon', '/', false, true],
        ['Departments', '/2017-18/departments', true, false, true],
        ['About', '/2017-18/about', false, false]
      ]



